### numpy.where函数的使用
` numpy.where`函数是`x if condition else y`的矢量化版本。
假设我们想要根据cond中的值选取xarr和yarr的值：当cond中的值为True时，选取xarr的值，否则从yarr中选取，列表推导式的写法如下：

In [2]:
import numpy as np

In [3]:
xarry = np.array([1.1,1.2,1.3,1.4])

In [4]:
yarry = np.array([2.1,2.2,2.3,2.4])

In [5]:
cond = np.array([True,False,True,False])

In [7]:
result = [(x if c else y) for x,y,c in zip(xarry, yarry,cond)]

In [8]:
result

[1.1, 2.2, 1.3, 2.4]

这里存在几个问题：
1. 它对大数组的处理速度慢
2. 无法用于多维数组

为解决以上问题，我们使用numpy.where，如下：

In [9]:
np.where(cond, xarry, yarry)

array([1.1, 2.2, 1.3, 2.4])

其中numpy.where中的第二和第三个参数不必是数组，也可以是标量值。在数据分析中，where通常的用法是：

In [10]:
arr = np.random.randn(4,4)

In [11]:
arr

array([[ 0.08066135,  0.89268024,  0.45464173, -0.53972428],
       [ 0.10662648, -2.04250941, -1.82085981, -0.49385273],
       [-0.23701154,  1.39598584,  0.98360866,  0.60492666],
       [-0.44489629,  0.83592614,  1.35719661, -0.26519113]])

In [12]:
np.where(arr>0, 2, -2)

array([[ 2,  2,  2, -2],
       [ 2, -2, -2, -2],
       [-2,  2,  2,  2],
       [-2,  2,  2, -2]])

In [13]:
np.where(arr>0, 2, arr)

array([[ 2.        ,  2.        ,  2.        , -0.53972428],
       [ 2.        , -2.04250941, -1.82085981, -0.49385273],
       [-0.23701154,  2.        ,  2.        ,  2.        ],
       [-0.44489629,  2.        ,  2.        , -0.26519113]])

传递给where的数组大小可以不相等。
来个有难度的逻辑，有两个布尔型数组cond1和cond2，进行如下操作 :

In [25]:
cond1 = np.array([True, False, True, False])
cond2 = np.array([True, False, True, False])

In [26]:
result = []
for i in range(4):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)

In [27]:
result

[0, 3, 0, 3]

In [29]:
np.where(cond1 & cond2, 0, 
    np.where(cond1,1,
        np.where(cond2, 2, 3)))

array([0, 3, 0, 3])