### Numpy的切片和索引
#### Numpy的切片
Numpy的索引是一个内容丰富的主题。当你将一个标量赋值给一个切片时（如arr[5:8]=12），该值会自动传播（也就是广播）到整个选区。跟列表的重要区别在于，数组切片是**原始数组的视图**，这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上。

> 注：Numpy的切片是在原数据上进行修改，未复制新数据


In [1]:
import numpy as np
arr = np.arange(10)

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5:8] = 12

In [4]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

如果想获得一份数组切片的拷贝，可以使用`arr[5:8].copy()`

#### 高维数组如何获取单个元素
两种方式，
1. 对各个元素进行递归访问;
2. 传到一个用逗号隔开的索引列表

In [5]:
arr_high_wei = np.array([[1,2,3],[3,4,5],[4,5,6]])

In [6]:
arr_high_wei[1,1]

4

In [7]:
arr_high_wei[1][1]

4

#### 高维数组如何获得低维度数组以及赋值
在多维数组中，如果省略后面的索引，则返回对象会是一个维度低一点的ndarray。因此,在2 * 2 * 3数组arr中

In [8]:
arr_low_wei = np.array([[[1,2,3],[2,3,5]],[[5,6,7],[2,4,2]]])

In [9]:
arr_low_wei

array([[[1, 2, 3],
        [2, 3, 5]],

       [[5, 6, 7],
        [2, 4, 2]]])

arr_low_wei[0]是一个2*3数组

In [11]:
arr_low_wei[0]

array([[1, 2, 3],
       [2, 3, 5]])

标量值和数组都可以赋值给arr_low_wei[0]：

In [12]:
old_arr0 = arr_low_wei[0].copy()

In [13]:
arr_low_wei[0]

array([[1, 2, 3],
       [2, 3, 5]])

In [14]:
arr_low_wei[0] = 48

In [15]:
arr_low_wei

array([[[48, 48, 48],
        [48, 48, 48]],

       [[ 5,  6,  7],
        [ 2,  4,  2]]])

In [16]:
arr_low_wei[0] = old_arr0

In [17]:
arr_low_wei

array([[[1, 2, 3],
        [2, 3, 5]],

       [[5, 6, 7],
        [2, 4, 2]]])

> 注：在上述这些选取子集的例子中，返回的数组都是视图

#### 高维度的切片索引
对于一维数组来说，其切片语法跟Python列表差不多：

In [18]:
arr[5:8]

array([12, 12, 12])

而对于二维数组来说，其切片方式就略有不同：

In [20]:
arr_high_wei

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [19]:
arr_high_wei[:2]

array([[1, 2, 3],
       [3, 4, 5]])

可以看出，它是沿着0轴（即第一个轴）切片的。也就是说，切片就是沿着一个轴向选取元素的。表达示arr_high_wei[:2]可以被认为是选取了表达示arr_high_wei的前两行。
你也可以一次传入多个切片，像传入多个索引那样：

In [21]:
arr_high_wei[:2,:2]

array([[1, 2],
       [3, 4]])

我们也可以将索引和切片相结合使用，如我们选取第二行的前两列：

In [22]:
arr_high_wei[1,:2]

array([3, 4])

下图有助于理解切片：
![](images/15777037-ffcc63c7a547e8f2.png)
#### 布尔型索引
假设我们有一个存储数据和存储姓名的数组，如下：

In [30]:
names = np.array(['li','hu','zhao','zhou','wang','zhao'])

In [24]:
datas = np.random.randn(3,6)

In [25]:
datas

array([[-1.15129786,  0.08202014,  0.322395  , -0.17085469, -0.36016072,
         1.49025963],
       [-0.02483223,  0.2550378 ,  1.03879756,  0.01846801, -0.81229238,
         2.19533334],
       [ 0.55540024,  1.2437431 , -0.34730149,  0.38398555, -0.31061721,
        -0.0385373 ]])

假设每个名字都对应datas数组中的一列，而我们想选出对应于名字‘zhao’的所有列。跟算术运算一样，数组的比较运算'=='也是矢量化的。因此names和字符串'zhao'的比较运算将会产生一个布尔型数组：

In [31]:
names == 'zhao'

array([False, False,  True, False, False,  True])

该布尔型数组可以用于数组索引：

In [32]:
datas[:,names == 'zhao']

array([[ 0.322395  ,  1.49025963],
       [ 1.03879756,  2.19533334],
       [-0.34730149, -0.0385373 ]])

> 注：布尔型数组的长度必须要与被索引的轴长度一致

此外，还可以将布尔型数组跟切片、整数（或整数序列）混合使用。
要选择除‘zhao’以外的其他值，可以使用不等号‘!=’或者使用`~`对条件进行否定：

In [33]:
datas[:,~(names == 'zhao')]

array([[-1.15129786,  0.08202014, -0.17085469, -0.36016072],
       [-0.02483223,  0.2550378 ,  0.01846801, -0.81229238],
       [ 0.55540024,  1.2437431 ,  0.38398555, -0.31061721]])

要想组合多个布尔型数组，可以使用`&`和`|`或之类的布尔算术运算即可：

In [34]:
(names == 'zhao') | (names == 'li')

array([ True, False,  True, False, False,  True])

> 注：Python关键字and和or在布尔型数组中无效。要使用`&`和`|`

使用布尔型数组设置值是一种很常见的用法，例如将所有小于0的数值都设置为0，就可以使用布尔型数组进行设置。

### 花式索引
花式索引是Numpy中的术语，用于描述使用整数数组进行数据索引。意思是：使用一个包含指明所需顺序的列表或数组，从某一个数组中选出一个符合特定顺序的子集。如下：

In [35]:
arr_hua = np.empty((8,4))

In [36]:
for i in range(8):
    arr_hua[i] = i

In [37]:
arr_hua

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [38]:
arr_hua[[3,2,1,0]]

array([[3., 3., 3., 3.],
       [2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.]])

使用负的索引则是从尾部进行选择。
当传递多个索引数组时则是根据每个索引元组对应的元素选出一个一维数组：

In [40]:
arr_hua2 = np.arange(32).reshape((8,4))

In [41]:
arr_hua2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [44]:
arr_hua2[[4,5,6,1],[1,0,1,2]]

array([17, 20, 25,  6])

In [45]:
arr_hua2[[4,5,6,1]][:,[1,0,1,2]]

array([[17, 16, 17, 18],
       [21, 20, 21, 22],
       [25, 24, 25, 26],
       [ 5,  4,  5,  6]])

可以看出最终选出的元素是(4,1),(5,0),(6,1),(1,2)
如果想要达到排序的效果，应该是矩形区域的形式才对，如上的方法
> 记住，花式索引跟切片不一样，它总是将数据复制到新数组中。