### reshape、flatten、ravel函数和C、Fortran顺序
#### reshape函数
1. 将原数组从一个形状转换为另一个形状
2. 传入的参数是`元组`
如下：

In [2]:
import numpy as np
arr_hua2 = np.arange(32).reshape((8,4))
arr_hua2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [3]:
arr_hua2.reshape(4,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

其中参数可以为-1，它表示该维充的大小由数据本身推断而来

In [4]:
arr_hua2.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

由于数组的shape是一个元组，所以它也可以传入reshape

#### flatten和ravel函数
这两个函数是reshape函数运算过程的相反运算,两者所要实现的功能是一致的（将多维数组降位一维），如下：

In [5]:
arr_hua2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

flatten和ravel函数的作用是相同的，它们的区别在于，ravel不会产生源数据的副本，它只是返回数组的视图，这样在修改视图的时候会影响原来的数据，而flatten()分配了新的内存，返回了数据的副本，所以我们在平时使用的时候，flatten函数更为安全，具体表现如下：

In [10]:
arr_hua2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [11]:
a = arr_hua2.flatten()

In [12]:
a[0] = 1

In [13]:
arr_hua2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [14]:
b = arr_hua2.ravel()

In [15]:
b[0] = 1

In [16]:
arr_hua2

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

#### C和Fortran顺序
行和列优先顺序又分别称为C和Fortran顺序，这里的行和列优行顺序是指数据在内存中的布局顺序。默认情况下，Numpy数组是按行优先顺序创建的。在空间方面，这就意味着，对于一个二维数组，每行中的数据项是被存放在相邻内存位置上的。而列优先顺序，意味着每列中的数据是被存放在相邻内存位置上的。
像reshape和ravel这样的函数，都可以接受一个表示数组数据存放顺序的order参数，一般是`C`或`F`（还有`A`和`K`），具体如下：

In [18]:
arr_hua2.ravel()

array([ 1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [20]:
arr_hua2.ravel('F')

array([ 1,  4,  8, 12, 16, 20, 24, 28,  1,  5,  9, 13, 17, 21, 25, 29,  2,
        6, 10, 14, 18, 22, 26, 30,  3,  7, 11, 15, 19, 23, 27, 31])

In [21]:
arr_hua2.flatten('F')

array([ 1,  4,  8, 12, 16, 20, 24, 28,  1,  5,  9, 13, 17, 21, 25, 29,  2,
        6, 10, 14, 18, 22, 26, 30,  3,  7, 11, 15, 19, 23, 27, 31])

In [22]:
arr_hua2.flatten()

array([ 1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

对于更高维度的数组，C和Fortran顺序的关键就是维度的行进顺序：
* C/行优先顺序：先经过更高的维度（例如：轴1会先于轴0被处理）
* Fortran/列优先顺序：后经过更高的维度（例如：轴0会先于轴1被处理）
![](images/15777037-2c5e5d26d0a290aa.png)