### 线性代数常见方法及库
#### 矩阵点积的三种方法
1. x.dot(y)
2. np.dot(x, y)
3. 使用中缀运算符`@`, x @ np.ons(3)如下：

In [3]:
import numpy as np
x = np.arange(10).reshape(2,5)

In [4]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
x @ np.ones(5)

array([10., 35.])

#### numpy.linalg库
nympy.linalg中有一组标准的矩阵分解运算以及诸如求逆和行列式之类的东西。它们跟Matlab和R语言使用的是相同的行业标准线性代数库，如BLAS、LAPACK、IntelMKL等：

In [7]:
from numpy.linalg import inv, qr

In [9]:
x_1 = np.random.randn(5,5)

In [10]:
x_1

array([[ 1.32874166,  1.00803803,  0.24590819,  1.28694237,  0.03249118],
       [-0.20879383, -0.2628231 , -1.24319026,  0.43761617, -0.07854425],
       [-2.50355122, -0.75698042, -0.51539269, -1.38794749,  0.03814209],
       [-0.49847529,  0.8905445 ,  0.22290324,  0.79893044, -1.40914028],
       [-1.19075521,  0.2906461 ,  0.53359514,  0.94167078, -1.48223096]])

In [11]:
inv(x_1)

array([[-0.68097113,  0.04819042, -0.66306593,  0.33736901, -0.35527636],
       [ 0.87194979, -0.29530118,  0.68890678,  0.89487999, -0.79826305],
       [ 0.11417067, -0.63408591, -0.0342542 , -0.51757055,  0.52727027],
       [ 0.74422382,  0.30600328,  0.13286087, -0.92836547,  0.88610393],
       [ 1.23194936, -0.1304803 ,  0.73983787, -0.87167137,  0.20698675]])

In [15]:
x_1.dot(inv(x_1))

array([[ 1.00000000e+00,  6.11745299e-17,  4.44870385e-16,
        -1.36379467e-17,  4.71173598e-17],
       [ 2.67342647e-17,  1.00000000e+00, -3.18102578e-17,
         2.40940250e-17, -5.37791819e-17],
       [-4.40756528e-17,  2.04460093e-18,  1.00000000e+00,
        -7.97730019e-17,  7.43558912e-17],
       [-1.65829551e-16, -2.32916705e-17, -1.39769964e-16,
         1.00000000e+00,  8.77192782e-17],
       [-1.65951086e-16, -1.02415102e-16, -1.82006395e-16,
         1.05440491e-16,  1.00000000e+00]])

In [13]:
q, r = qr(x_1)

In [14]:
r

array([[-3.12142492, -0.80073508, -0.36205835, -1.14495579, -0.77896383],
       [ 0.        ,  1.37644615,  0.7471748 ,  1.67190708, -1.66001965],
       [ 0.        ,  0.        ,  1.23153388, -0.4022829 , -0.04932185],
       [ 0.        ,  0.        ,  0.        , -1.01544667,  0.69269782],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.58877145]])

下表给出一些常用的numpy.linalg函数
![](images/15777037-9943bacb2a82643f.png)