### 转置和轴对换
转置返回的是源数据的视图（不会进行任何复制操作）。数组可以使用`transpose方法`或者`T属性`转置，如下：

In [1]:
import numpy as np

In [4]:
arr = np.arange(15).reshape((3,5))

#### 利用T属性进行转置

In [5]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [7]:
np.dot(arr.T,arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

#### transpose方法进行轴对换
`transpose`方法需要得到一个轴编号组成的元组才能对这些轴进行转置，如下：

In [9]:
arr.transpose((1,0))

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#### swapaxes方法
ndarray还有一个`swapaxes`方法，它需要接受一对轴编号：

In [10]:
arr.swapaxes(1,0)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

高维度的情况下，使用**swapaxes**的情况，如下：（较难想象）

In [12]:
arr_high_wei = np.array([[[0,1,2,3],[4,5,6,7]],[[8,9,10,11],[12,13,14,15]]])

In [13]:
arr_high_wei

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [14]:
arr_high_wei.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

`swapaxes`也是返回源数据的视图（不会进行任何复制操作）