### 通用函数：快速的元素级数组函数
通用函数是一对ndarray中的数据执行元素级运算的函数。可以将它作为简单函数的矢量化包装器。它包括一元的：

In [1]:
import numpy as np
arr = np.arange(11)

In [2]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

二元，返回一个结果数组的：

In [5]:
x = np.random.randn(9)
y = np.random.randn(9)

In [6]:
x

array([-2.06701496,  0.87910141,  0.15011424, -1.24570964, -0.23154642,
        0.44488205, -1.15359442,  0.56796375, -1.20338673])

In [7]:
y

array([-1.16708541, -0.52403299,  0.47360619, -0.27719614, -0.39159525,
        0.57629666,  1.30062581,  2.17803811, -1.05153709])

In [8]:
np.maximum(x,y)

array([-1.16708541,  0.87910141,  0.47360619, -0.27719614, -0.23154642,
        0.57629666,  1.30062581,  2.17803811, -1.05153709])

返回多个数组的：

In [9]:
arr = np.random.randn(9)*5

In [10]:
arr 

array([ 2.45656237,  8.90801749, -4.39257839, -0.77013745, -5.72741076,
       -1.87933141, -1.2328695 , -3.68226089, -4.87730319])

In [11]:
remainder, whole_part = np.modf(arr)

In [12]:
remainder

array([ 0.45656237,  0.90801749, -0.39257839, -0.77013745, -0.72741076,
       -0.87933141, -0.2328695 , -0.68226089, -0.87730319])

In [13]:
whole_part

array([ 2.,  8., -4., -0., -5., -1., -1., -3., -4.])

通用函数可以接受一个out可选参数，这样就能在数组原地进行操作：

In [14]:
np.sqrt(arr)

c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.56734246, 2.98463021,        nan,        nan,        nan,
              nan,        nan,        nan,        nan])

In [15]:
arr

array([ 2.45656237,  8.90801749, -4.39257839, -0.77013745, -5.72741076,
       -1.87933141, -1.2328695 , -3.68226089, -4.87730319])

In [16]:
np.sqrt(arr,arr)

c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.56734246, 2.98463021,        nan,        nan,        nan,
              nan,        nan,        nan,        nan])

In [17]:
arr

array([1.56734246, 2.98463021,        nan,        nan,        nan,
              nan,        nan,        nan,        nan])

下表列出了一些一元和二元通用函数
![](images/15777037-fa8cbcbc9d6c9be7.png)
![](images/15777037-a44c7d1c616f9b04.png)
![](images/15777037-ac3bd85f241d6bb4.png)